USE [master]
GO
/****** Object:  Database [Atelier]    Script Date: 26-01-2020 3:31:27 PM ******/
CREATE DATABASE [Atelier]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Atelier', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Atelier.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Atelier_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Atelier_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Atelier] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Atelier].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Atelier] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Atelier] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Atelier] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Atelier] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Atelier] SET ARITHABORT OFF 
GO
ALTER DATABASE [Atelier] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Atelier] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Atelier] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Atelier] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Atelier] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Atelier] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Atelier] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Atelier] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Atelier] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Atelier] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Atelier] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Atelier] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Atelier] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Atelier] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Atelier] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Atelier] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Atelier] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Atelier] SET RECOVERY FULL 
GO
ALTER DATABASE [Atelier] SET  MULTI_USER 
GO
ALTER DATABASE [Atelier] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Atelier] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Atelier] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Atelier] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Atelier] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Atelier', N'ON'
GO
ALTER DATABASE [Atelier] SET QUERY_STORE = OFF
GO
USE [Atelier]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Atelier]
GO
/****** Object:  Table [dbo].[CountryTaxes]    Script Date: 26-01-2020 3:31:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CountryTaxes](
	[TaxId] [int] NOT NULL,
	[Country] [nvarchar](2) NOT NULL,
	[Percentual] [decimal](10, 4) NULL,
 CONSTRAINT [PK_CountryTaxes] PRIMARY KEY CLUSTERED 
(
	[TaxId] ASC,
	[Country] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Customer]    Script Date: 26-01-2020 3:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] NOT NULL,
	[Country] [nvarchar](2) NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[OrderItems]    Script Date: 26-01-2020 3:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItems](
	[Code] [nvarchar](50) NOT NULL,
	[Price] [decimal](10, 4) NULL,
	[Description] [nvarchar](50) NULL,
	[Order_Id] [int] NOT NULL,
	[Quantity] [decimal](10, 4) NULL,
 CONSTRAINT [PK_OrderItems] PRIMARY KEY CLUSTERED 
(
	[Code] ASC,
	[Order_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Orders]    Script Date: 26-01-2020 3:31:29 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] NOT NULL,
	[Total] [decimal](10, 4) NULL,
	[Customer_Id] [int] NULL,
	[TotalTax] [decimal](10, 4) NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[OrderItems]  WITH CHECK ADD  CONSTRAINT [FK_OrderItems_Orders] FOREIGN KEY([Order_Id])
REFERENCES [dbo].[Orders] ([Id])
GO
ALTER TABLE [dbo].[OrderItems] CHECK CONSTRAINT [FK_OrderItems_Orders]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Customer] FOREIGN KEY([Customer_Id])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Customer]
GO
USE [master]
GO
ALTER DATABASE [Atelier] SET  READ_WRITE 
GO
